"""alteracao tabela de games

Revision ID: 86bc05aad96b
Revises: 9bda469f6656
Create Date: 2022-06-28 15:07:06.396732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86bc05aad96b'
down_revision = '9bda469f6656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('name', sa.String(length=150), nullable=False))
    op.add_column('game', sa.Column('logo_url', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'logo_url')
    op.drop_column('game', 'name')
    # ### end Alembic commands ###
